# Site settings
title: Mortticia
description: 'True heavy metal to the modern world'
url: 'https://mortticia.rocks'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Mortticia'
  twitter_username: mortticiametal
  instagram_username: mortticia.official
  facebook_username: mortticia.official
  youtube_channel: UCIFeUby17-fzxNXec4SFRUw

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate_path: "/blog/page:num/"
paginate: 10
permalink: /:year-:month-:day/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
