# Site settings
title: Mortticia
description: 'True heavy metal to the modern world'
url: 'http://mortticia.xyz'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Mortticia'
  email: mortticia@mortticia.xyz
  twitter_username: mortticiaPOA
  facebook_username: MortticiaPOA
  lastfm_page: Mortticia
  youtube_channel: UCIFeUby17-fzxNXec4SFRUw

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
